import Head from 'next/head';
import Image from 'next/image';
import type { NextPageWithLayout, GetStaticProps } from 'next';
// components
import Banner from '@component/banner/Banner';
import AppLayout from '@component/layouts/AppLayout';
// styles
import styles from '@style/home.module.css';
import Card from '@component/card/Card';
// JSON
import coffeeStoresDummyData from '@data/coffee-stores.json';
// interfaces
import ICoffeeStore from 'interfaces/ICoffeeStore';

export const getStaticProps: GetStaticProps = async ({}) => {
  return {
    props: { coffeeStores: coffeeStoresDummyData },
  };
};

const Home: NextPageWithLayout<{ coffeeStores: ICoffeeStore[] }> = ({ coffeeStores }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        {/* <meta name='description' content='Generated by create next app' /> */}
        <link rel='icon' href='/static/background.png' />
      </Head>
      <main className={styles.main}>
        <Banner buttonText='View stores nearby' handleOnClick={() => console.log('hello there')} />
        <div className={styles.heroImage}>
          <Image src='/static/hero-image.png' alt='' width={700} height={400} />
        </div>
        {!!coffeeStores.length && (
          <>
            <h2 className={styles.heading2}>Toronto stores</h2>
            <div className={styles.cardLayout}>
              {coffeeStores?.map((coffeeStore: ICoffeeStore) => (
                <Card key={coffeeStore?.id} className={styles.card} coffeeStore={coffeeStore} />
              ))}
            </div>
          </>
        )}
      </main>
    </div>
  );
};

// Home.getLayout = function getLayout(page: ReactElement) {
//   return <AppLayout>{page}</AppLayout>;
// };

Home.layout = AppLayout;

export default Home;
