import Head from 'next/head';
import Image from 'next/image';
import type {
  NextPageWithLayout,
  GetStaticProps,
  GetStaticPathsContext,
  GetStaticPropsResult,
} from 'next';
// components
import Banner from '@component/banner/Banner';
// layout
import AppLayout from '@component/layouts/AppLayout';
// styles
import styles from '@style/home.module.css';
import Card from '@component/card/Card';
// interfaces
import { fetchPlaces } from 'lib/fetch-places';
import { QueryResponse } from 'interfaces/response';
import { IPlace } from 'interfaces/IPlace';
import prepPlaces from 'lib/prep-places';

type Props = {
  data: QueryResponse<IPlace>;
};

const Home: NextPageWithLayout<Props> = ({ data }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        {/* <meta name='description' content='Generated by create next app' /> */}
        <link rel='icon' href='/static/background.png' />
      </Head>
      <main className={styles.main}>
        <Banner buttonText='View stores nearby' handleOnClick={() => console.log('hello there')} />
        <div className={styles.heroImage}>
          <Image src='/static/hero-image.png' alt='' width={700} height={400} />
        </div>
        {!!data?.results?.length && (
          <>
            <h2 className={styles.heading2}>Venues</h2>
            <div className={styles.cardLayout}>
              {data.results.map((entity: IPlace) => (
                <Card key={entity?.fsq_id} className={styles.card} entity={entity} />
              ))}
            </div>
          </>
        )}
      </main>
    </div>
  );
};

export const getStaticProps: GetStaticProps = async ({}: GetStaticPathsContext): Promise<
  GetStaticPropsResult<Props>
> => {
  const data = await fetchPlaces({
    categories: '13032,13033,13034,13035,13063,13036,11126',
    near: 'Santo Domingo',
    limit: 6,
  });

  return {
    props: { data },
  };
};

// Home.getLayout = function getLayout(page: ReactElement) {
//   return <AppLayout>{page}</AppLayout>;
// };

Home.layout = AppLayout;

export default Home;
